# Just apply Travis-CI for these branches
branches:
  only:
  - master
  - experimental

language: node_js

node_js:
- 6
- 8
- 10

install:
- cd client/ && npm install && cd ..
- cd server/ && npm install && cd ..
- cd test/ && npm install && cd ..

script:
- cd client/ && npm run lint && cd ..
- cd server/ && npm run lint && cd ..
- cd test/ && npm run lint && npm test

notifications:
  email:
    recipients:
      - ibc@aliax.net
    on_success: change
    on_failure: always
